site_name: MDS-2020-2-G5
site_description: Reposit처rio do Grupo 05
repo_url: https://github.com/fga-eps-mds/MDS-2020-2-G5.git

theme:
    name: mkdocs


plugins:
    - search

nav:
    - Home: "index.md"
    - Sprints:
        - Sprint 0:
            - Planejamento: sprints/planejamento-sprint-0.md
            - Revis찾o: sprints/revisao-sprint-0.md
        - Sprint 1:
            - Planejamento: sprints/planejamento-sprint-1.md
            - Revis찾o: sprints/revisao-sprint-1.md
        - Sprint 2:
            - Planejamento: sprints/planejamento-sprint-2.md
            - Revis찾o: sprints/revisao-sprint-2.md
